### PR TITLE
Switch Batocera base image to bcm2837 (Pi3/Zero2)

### PR DESCRIPTION
**Pull request by TobiX**
Both, Batocera's bcm2836 & bcm2837 build are designed to support the Zero2, but the differ in the shipped kernel: The bcm2836 image contains a 32-bit kernel and the bcm2837 image contains a 64-bit kernel.

This is mostly a small experiment: As I noted in https://github.com/CoryManson/PSPi-Version-6/pull/15#issuecomment-2113492112, the Batocera build use as a base for our images contains a 32-bit kernel - let's try a build with a 64-bit kernel instead...

### CODE REVIEW

**Comment by CoryManson** [comment]
Let me fix up these builds so we can get some artifacts without a merge to main. 

I'm happy to use either a 32 bit or 64 bit build image for Batocera zero 2 but good catch, for some reason I had assumed the bcm2836 source was 64 bit so the config.txt would absolutely be incorrect.

**Comment by CoryManson** [comment]
If you can please re-sync your branch with my main, we should get actions running correctly.

**Comment by CoryManson** [comment]
Sorry, one more time hopefully! There's a few things on the workflow that seems to only work from my repo. (Most of my experience is with azure devops and rarely with forks)

We should hope to see new images show up as build artifacts on the action run which you can then download and test.

**Comment by TobiX** [comment]
Yay, a build! And it boots! And works!

**Comment by CoryManson** [comment]
Awesome! Thanks for helping! I haven't had much time in the past week or so to get everything stable.

**Pull request merged**
